map_name = {
    "code_ISIN": "ISIN",
    "nom_du_produit": "Nom du produit",
    "emetteur_du_produit": "Emetteur",
    "date_emission": "Date émission",
    "date_remboursement": "Date remboursement",
    "mention_complexite": "Mention complexité",
    "montant_minimum_investissement": "Montant investissement minimum",
    "niveau_garantie": "Niveau de garantie", 
    "niveau_barriere_desactivante": "Niveau barrière désactivante",
    "niveau_risque": "Niveau de risque",
    "produit_sous_jacent": "Sous jacent",
    "nature_sous_jacent": "Nature sous-jacent",
    "code_ISIN_sous_jacent": "ISIN du sous-jacent",
    "frais_ponctuels_entree": "Frais ponctuels : entrée",
    "frais_ponctuels_sortie_echeance": "Frais ponctuels : sortie à l\'échéance",
    "frais_ponctuels_sortie_anticipee": "Frais ponctuels: sortie anticicpée",
    "frais_recurrents": "Frais récurrents",
    "frais_accessoires": "Frais accessoires",
    "performance_tension": "Performance: scnéario de tension",
    "performance_maximale": "Performance maximale",
    "espérance_maximale_rendement": "Espérance maximale de rendement",
    "date_actualisation": "Date actualisation",
    "resume_mecanisme": "Résumé du mécanisme",
    "resume_detaille_mecanisme": "Résumé détaillé mécanisme",
    "complexite_gpt": "Commplexité GPT"

}